// Категории Дзен, RB.ru, Хабр и Лайфхакер
window.DZEN_CATEGORIES = {
    "Авто": "https://dzen.ru/news/rubric/auto",
    "В мире": "https://dzen.ru/news/rubric/world",
    "Главное": "https://dzen.ru/news",
    "Интересное": "https://dzen.ru/news/rubric/personal_feed",
    "Культура": "https://dzen.ru/news/rubric/culture",
    "Москва": "https://dzen.ru/news/region/moscow",
    "Наука": "https://dzen.ru/news/rubric/science",
    "Общество": "https://dzen.ru/news/rubric/society",
    "Политика": "https://dzen.ru/news/rubric/politics",
    "Происшествия": "https://dzen.ru/news/rubric/incident",
    "СВО": "https://dzen.ru/news/rubric/svo",
    "Спорт": "https://sportsdzen.ru/news/rubric/sport",
    "Технологии": "https://dzen.ru/news/rubric/computers",
    "Шоу-бизнес": "https://dzen.ru/news/rubric/showbusiness",
    "Экономика": "https://dzen.ru/news/rubric/business"
};

window.RB_CATEGORIES = {
    "Банки": "https://rb.ru/tag/banking/",
    "Бизнес": "https://rb.ru/tag/business/",
    "Дизайн": "https://rb.ru/tag/design/",
    "Деньги": "https://rb.ru/tag/money/",
    "ИИ": "https://rb.ru/tag/ai/",
    "IT": "https://rb.ru/tag/it/",
    "Карьера": "https://rb.ru/tag/career/",
    "Кибербезопасность": "https://rb.ru/tag/cybersecurity/",
    "Личное": "https://rb.ru/tag/personal/",
    "Маркетинг": "https://rb.ru/tag/marketing/",
    "Маркетплейсы": "https://rb.ru/tag/marketplaces/",
    "Реклама": "https://rb.ru/tag/advertising/",
    "Ритейл": "https://rb.ru/tag/retail/",
    "Россия": "https://rb.ru/tag/russia/",
    "Стартапы": "https://rb.ru/tag/startups/",
    "Технологии": "https://rb.ru/tag/technology/",
    "Тренды": "https://rb.ru/tag/trends/",
    "HR": "https://rb.ru/tag/hr/"
};

window.HABR_CATEGORIES = {
    "1C": "https://habr.com/ru/rss/hubs/1C/articles/",
    "3d_graphics": "https://habr.com/ru/rss/hubs/3d_graphics/articles/",
    "3d-printers": "https://habr.com/ru/rss/hubs/3d-printers/articles/",
    "accessibility": "https://habr.com/ru/rss/hubs/accessibility/articles/",
    "action_script": "https://habr.com/ru/rss/hubs/action_script/articles/",
    "advent2024": "https://habr.com/ru/rss/hubs/advent2024/articles/",
    "agile": "https://habr.com/ru/rss/hubs/agile/articles/",
    "AI": "https://habr.com/ru/rss/hubs/artificial_intelligence/articles/",
    "AJAX": "https://habr.com/ru/rss/hubs/AJAX/articles/",
    "algorithms": "https://habr.com/ru/rss/hubs/algorithms/articles/",
    "android_dev": "https://habr.com/ru/rss/hubs/android_dev/articles/",
    "angular": "https://habr.com/ru/rss/hubs/angular/articles/",
    "animation": "https://habr.com/ru/rss/hubs/animation/articles/",
    "antikvariat": "https://habr.com/ru/rss/hubs/antikvariat/articles/",
    "apache": "https://habr.com/ru/rss/hubs/apache/articles/",
    "api": "https://habr.com/ru/rss/hubs/api/articles/",
    "apps_design": "https://habr.com/ru/rss/hubs/apps_design/articles/",
    "arduino": "https://habr.com/ru/rss/hubs/arduino/articles/",
    "artificial_intelligence": "https://habr.com/ru/rss/hubs/artificial_intelligence/articles/",
    "arvr": "https://habr.com/ru/rss/hubs/arvr/articles/",
    "asp": "https://habr.com/ru/rss/hubs/asp/articles/",
    "assembler": "https://habr.com/ru/rss/hubs/assembler/articles/",
    "asterisk": "https://habr.com/ru/rss/hubs/asterisk/articles/",
    "astronomy": "https://habr.com/ru/rss/hubs/astronomy/articles/",
    "Atlassian": "https://habr.com/ru/rss/hubs/Atlassian/articles/",
    "autogadgets": "https://habr.com/ru/rss/hubs/autogadgets/articles/",
    "aws": "https://habr.com/ru/rss/hubs/aws/articles/",
    "azure": "https://habr.com/ru/rss/hubs/azure/articles/",
    "backup": "https://habr.com/ru/rss/hubs/backup/articles/",
    "bada_dev": "https://habr.com/ru/rss/hubs/bada_dev/articles/",
    "bigdata": "https://habr.com/ru/rss/hubs/bigdata/articles/",
    "billing": "https://habr.com/ru/rss/hubs/billing/articles/",
    "biology": "https://habr.com/ru/rss/hubs/biology/articles/",
    "biotech": "https://habr.com/ru/rss/hubs/biotech/articles/",
    "bitrix": "https://habr.com/ru/rss/hubs/bitrix/articles/",
    "brain": "https://habr.com/ru/rss/hubs/brain/articles/",
    "brainfuck": "https://habr.com/ru/rss/hubs/brainfuck/articles/",
    "branding": "https://habr.com/ru/rss/hubs/branding/articles/",
    "browser_extensions": "https://habr.com/ru/rss/hubs/browser_extensions/articles/",
    "browsers": "https://habr.com/ru/rss/hubs/browsers/articles/",
    "bughunters": "https://habr.com/ru/rss/hubs/bughunters/articles/",
    "build_automation": "https://habr.com/ru/rss/hubs/build_automation/articles/",
    "business-laws": "https://habr.com/ru/rss/hubs/business-laws/articles/",
    "business_models": "https://habr.com/ru/rss/hubs/business_models/articles/",
    "c": "https://habr.com/ru/rss/hubs/c/articles/",
    "cad_cam": "https://habr.com/ru/rss/hubs/cad_cam/articles/",
    "cakephp": "https://habr.com/ru/rss/hubs/cakephp/articles/",
    "canvas": "https://habr.com/ru/rss/hubs/canvas/articles/",
    "career": "https://habr.com/ru/rss/hubs/career/articles/",
    "cellular": "https://habr.com/ru/rss/hubs/cellular/articles/",
    "cgi": "https://habr.com/ru/rss/hubs/cgi/articles/",
    "Chemistry": "https://habr.com/ru/rss/hubs/Chemistry/articles/",
    "circuit-design": "https://habr.com/ru/rss/hubs/circuit-design/articles/",
    "cisconetworks": "https://habr.com/ru/rss/hubs/cisconetworks/articles/",
    "client_side_optimization": "https://habr.com/ru/rss/hubs/client_side_optimization/articles/",
    "clojure": "https://habr.com/ru/rss/hubs/clojure/articles/",
    "closet": "https://habr.com/ru/rss/hubs/closet/articles/",
    "cloud_computing": "https://habr.com/ru/rss/hubs/cloud_computing/articles/",
    "cloud_services": "https://habr.com/ru/rss/hubs/cloud_services/articles/",
    "cms": "https://habr.com/ru/rss/hubs/cms/articles/",
    "cobol": "https://habr.com/ru/rss/hubs/cobol/articles/",
    "code_wtf": "https://habr.com/ru/rss/hubs/code_wtf/articles/",
    "codeigniter": "https://habr.com/ru/rss/hubs/codeigniter/articles/",
    "coffeescript": "https://habr.com/ru/rss/hubs/coffeescript/articles/",
    "community_management": "https://habr.com/ru/rss/hubs/community_management/articles/",
    "compilers": "https://habr.com/ru/rss/hubs/compilers/articles/",
    "complete_code": "https://habr.com/ru/rss/hubs/complete_code/articles/",
    "contentmarketing": "https://habr.com/ru/rss/hubs/contentmarketing/articles/",
    "context": "https://habr.com/ru/rss/hubs/context/articles/",
    "controllers": "https://habr.com/ru/rss/hubs/controllers/articles/",
    "conversion": "https://habr.com/ru/rss/hubs/conversion/articles/",
    "copyright": "https://habr.com/ru/rss/hubs/copyright/articles/",
    "cpp": "https://habr.com/ru/rss/hubs/cpp/articles/",
    "crm": "https://habr.com/ru/rss/hubs/crm/articles/",
    "crypto": "https://habr.com/ru/rss/hubs/crypto/articles/",
    "cryptocurrency": "https://habr.com/ru/rss/hubs/cryptocurrency/articles/",
    "csharp": "https://habr.com/ru/rss/hubs/csharp/articles/",
    "css": "https://habr.com/ru/rss/hubs/css/articles/",
    "ctf": "https://habr.com/ru/rss/hubs/ctf/articles/",
    "cubrid": "https://habr.com/ru/rss/hubs/cubrid/articles/",
    "cvs": "https://habr.com/ru/rss/hubs/cvs/articles/",
    "cyberpunk": "https://habr.com/ru/rss/hubs/cyberpunk/articles/",
    "cybersport": "https://habr.com/ru/rss/hubs/cybersport/articles/",
    "d": "https://habr.com/ru/rss/hubs/d/articles/",
    "data_compression": "https://habr.com/ru/rss/hubs/data_compression/articles/",
    "data_engineering": "https://habr.com/ru/rss/hubs/data_engineering/articles/",
    "data_mining": "https://habr.com/ru/rss/hubs/data_mining/articles/",
    "data_recovery": "https://habr.com/ru/rss/hubs/data_recovery/articles/",
    "data_visualization": "https://habr.com/ru/rss/hubs/data_visualization/articles/",
    "db_admins": "https://habr.com/ru/rss/hubs/db_admins/articles/",
    "debug": "https://habr.com/ru/rss/hubs/debug/articles/",
    "delphi": "https://habr.com/ru/rss/hubs/delphi/articles/",
    "demoscene": "https://habr.com/ru/rss/hubs/demoscene/articles/",
    "derbyjs": "https://habr.com/ru/rss/hubs/derbyjs/articles/",
    "design": "https://habr.com/ru/rss/hubs/design/articles/",
    "desktop_environment": "https://habr.com/ru/rss/hubs/desktop_environment/articles/",
    "desktops": "https://habr.com/ru/rss/hubs/desktops/articles/",
    "dev_management": "https://habr.com/ru/rss/hubs/dev_management/articles/",
    "devcloud": "https://habr.com/ru/rss/hubs/devcloud/articles/",
    "devmail": "https://habr.com/ru/rss/hubs/devmail/articles/",
    "devops": "https://habr.com/ru/rss/hubs/devops/articles/",
    "devrel": "https://habr.com/ru/rss/hubs/devrel/articles/",
    "displays": "https://habr.com/ru/rss/hubs/displays/articles/",
    "distributed_systems": "https://habr.com/ru/rss/hubs/distributed_systems/articles/",
    "DIY": "https://habr.com/ru/rss/hubs/DIY/articles/",
    "django": "https://habr.com/ru/rss/hubs/django/articles/",
    "dns": "https://habr.com/ru/rss/hubs/dns/articles/",
    "dwh": "https://habr.com/ru/rss/hubs/dwh/articles/",
    "easyelectronics": "https://habr.com/ru/rss/hubs/easyelectronics/articles/",
    "Ecology": "https://habr.com/ru/rss/hubs/Ecology/articles/",
    "ecm": "https://habr.com/ru/rss/hubs/ecm/articles/",
    "ecommerce": "https://habr.com/ru/rss/hubs/ecommerce/articles/",
    "ecommerce_development": "https://habr.com/ru/rss/hubs/ecommerce_development/articles/",
    "edge": "https://habr.com/ru/rss/hubs/edge/articles/",
    "edu": "https://habr.com/ru/rss/hubs/edu/articles/",
    "electronics": "https://habr.com/ru/rss/hubs/electronics/articles/",
    "elixirphoenix": "https://habr.com/ru/rss/hubs/elixirphoenix/articles/",
    "elm": "https://habr.com/ru/rss/hubs/elm/articles/",
    "emailmarketing": "https://habr.com/ru/rss/hubs/emailmarketing/articles/",
    "emacs": "https://habr.com/ru/rss/hubs/emacs/articles/",
    "emberjs": "https://habr.com/ru/rss/hubs/emberjs/articles/",
    "energy": "https://habr.com/ru/rss/hubs/energy/articles/",
    "engineering_systems": "https://habr.com/ru/rss/hubs/engineering_systems/articles/",
    "erlang": "https://habr.com/ru/rss/hubs/erlang/articles/",
    "erp": "https://habr.com/ru/rss/hubs/erp/articles/",
    "excel": "https://habr.com/ru/rss/hubs/excel/articles/",
    "extjs": "https://habr.com/ru/rss/hubs/extjs/articles/",
    "facebook_api": "https://habr.com/ru/rss/hubs/facebook_api/articles/",
    "fido": "https://habr.com/ru/rss/hubs/fido/articles/",
    "finance": "https://habr.com/ru/rss/hubs/finance/articles/",
    "firebird": "https://habr.com/ru/rss/hubs/firebird/articles/",
    "firefox": "https://habr.com/ru/rss/hubs/firefox/articles/",
    "flash_platform": "https://habr.com/ru/rss/hubs/flash_platform/articles/",
    "flask": "https://habr.com/ru/rss/hubs/flask/articles/",
    "flex": "https://habr.com/ru/rss/hubs/flex/articles/",
    "flutter": "https://habr.com/ru/rss/hubs/flutter/articles/",
    "fpga": "https://habr.com/ru/rss/hubs/fpga/articles/",
    "forth": "https://habr.com/ru/rss/hubs/forth/articles/",
    "fortran": "https://habr.com/ru/rss/hubs/fortran/articles/",
    "fsharp": "https://habr.com/ru/rss/hubs/fsharp/articles/",
    "funcprog": "https://habr.com/ru/rss/hubs/funcprog/articles/",
    "futurenow": "https://habr.com/ru/rss/hubs/futurenow/articles/",
    "gadgets": "https://habr.com/ru/rss/hubs/gadgets/articles/",
    "gae": "https://habr.com/ru/rss/hubs/gae/articles/",
    "game_design": "https://habr.com/ru/rss/hubs/game_design/articles/",
    "game_monetization": "https://habr.com/ru/rss/hubs/game_monetization/articles/",
    "game_promotion": "https://habr.com/ru/rss/hubs/game_promotion/articles/",
    "game_testing": "https://habr.com/ru/rss/hubs/game_testing/articles/",
    "gamedev": "https://habr.com/ru/rss/hubs/gamedev/articles/",
    "games": "https://habr.com/ru/rss/hubs/games/articles/",
    "gcp": "https://habr.com/ru/rss/hubs/googlecloud/articles/",
    "geo": "https://habr.com/ru/rss/hubs/geo/articles/",
    "geo_systems": "https://habr.com/ru/rss/hubs/geo_systems/articles/",
    "git": "https://habr.com/ru/rss/hubs/git/articles/",
    "github": "https://habr.com/ru/rss/hubs/github/articles/",
    "go": "https://habr.com/ru/rss/hubs/go/articles/",
    "godot": "https://habr.com/ru/rss/hubs/godot/articles/",
    "google_api": "https://habr.com/ru/rss/hubs/google_api/articles/",
    "google_chrome": "https://habr.com/ru/rss/hubs/google_chrome/articles/",
    "google_cloud_vision_api": "https://habr.com/ru/rss/hubs/google_cloud_vision_api/articles/",
    "google_sheets": "https://habr.com/ru/rss/hubs/google_sheets/articles/",
    "googlecloud": "https://habr.com/ru/rss/hubs/googlecloud/articles/",
    "gpgpu": "https://habr.com/ru/rss/hubs/gpgpu/articles/",
    "gradle": "https://habr.com/ru/rss/hubs/gradle/articles/",
    "graph_design": "https://habr.com/ru/rss/hubs/graph_design/articles/",
    "greasemonkey": "https://habr.com/ru/rss/hubs/greasemonkey/articles/",
    "groovy_grails": "https://habr.com/ru/rss/hubs/groovy_grails/articles/",
    "growthhacking": "https://habr.com/ru/rss/hubs/growthhacking/articles/",
    "gtk": "https://habr.com/ru/rss/hubs/gtk/articles/",
    "gtd": "https://habr.com/ru/rss/hubs/gtd/articles/",
    "gwt": "https://habr.com/ru/rss/hubs/gwt/articles/",
    "habr": "https://habr.com/ru/rss/hubs/habr/articles/",
    "hackathons": "https://habr.com/ru/rss/hubs/hackathons/articles/",
    "Hadoop": "https://habr.com/ru/rss/hubs/Hadoop/articles/",
    "hardware": "https://habr.com/ru/rss/hubs/hardware/articles/",
    "haskell": "https://habr.com/ru/rss/hubs/haskell/articles/",
    "haxe": "https://habr.com/ru/rss/hubs/haxe/articles/",
    "health": "https://habr.com/ru/rss/hubs/health/articles/",
    "helpdesk": "https://habr.com/ru/rss/hubs/helpdesk/articles/",
    "hi": "https://habr.com/ru/rss/hubs/hi/articles/",
    "history": "https://habr.com/ru/rss/hubs/history/articles/",
    "home_automation": "https://habr.com/ru/rss/hubs/home_automation/articles/",
    "hosting": "https://habr.com/ru/rss/hubs/hosting/articles/",
    "htmx": "https://habr.com/ru/rss/hubs/htmx/articles/",
    "html5": "https://habr.com/ru/rss/hubs/html5/articles/",
    "i2p": "https://habr.com/ru/rss/hubs/i2p/articles/",
    "i_am_advertising": "https://habr.com/ru/rss/hubs/i_am_advertising/articles/",
    "iconoskaz": "https://habr.com/ru/rss/hubs/iconoskaz/articles/",
    "ie": "https://habr.com/ru/rss/hubs/ie/articles/",
    "image_processing": "https://habr.com/ru/rss/hubs/image_processing/articles/",
    "industrial_control_system": "https://habr.com/ru/rss/hubs/industrial_control_system/articles/",
    "infographics": "https://habr.com/ru/rss/hubs/infographics/articles/",
    "infolust": "https://habr.com/ru/rss/hubs/infolust/articles/",
    "infosecurity": "https://habr.com/ru/rss/hubs/infosecurity/articles/",
    "instant_messaging": "https://habr.com/ru/rss/hubs/instant_messaging/articles/",
    "internetmarketing": "https://habr.com/ru/rss/hubs/internetmarketing/articles/",
    "internet_of_things": "https://habr.com/ru/rss/hubs/internet_of_things/articles/",
    "interviews": "https://habr.com/ru/rss/hubs/interviews/articles/",
    "ios_dev": "https://habr.com/ru/rss/hubs/ios_dev/articles/",
    "IPFS": "https://habr.com/ru/rss/hubs/IPFS/articles/",
    "iptv": "https://habr.com/ru/rss/hubs/iptv/articles/",
    "ipv6": "https://habr.com/ru/rss/hubs/ipv6/articles/",
    "iis": "https://habr.com/ru/rss/hubs/iis/articles/",
    "it-immigration": "https://habr.com/ru/rss/hubs/it_immigration/articles/",
    "it-infrastructure": "https://habr.com/ru/rss/hubs/it-infrastructure/articles/",
    "it_biography": "https://habr.com/ru/rss/hubs/it_biography/articles/",
    "it_monetization": "https://habr.com/ru/rss/hubs/it_monetization/articles/",
    "it_testing": "https://habr.com/ru/rss/hubs/it_testing/articles/",
    "itcompanies": "https://habr.com/ru/rss/hubs/itcompanies/articles/",
    "itstandarts": "https://habr.com/ru/rss/hubs/itstandarts/articles/",
    "java": "https://habr.com/ru/rss/hubs/java/articles/",
    "javascript": "https://habr.com/ru/rss/hubs/javascript/articles/",
    "javame_dev": "https://habr.com/ru/rss/hubs/javame_dev/articles/",
    "jetpack-compose": "https://habr.com/ru/rss/hubs/jetpack-compose/articles/",
    "joomla": "https://habr.com/ru/rss/hubs/joomla/articles/",
    "jquery": "https://habr.com/ru/rss/hubs/jquery/articles/",
    "julia": "https://habr.com/ru/rss/hubs/julia/articles/",
    "kohanaphp": "https://habr.com/ru/rss/hubs/kohanaphp/articles/",
    "kotlin": "https://habr.com/ru/rss/hubs/kotlin/articles/",
    "kubernetes": "https://habr.com/ru/rss/hubs/kubernetes/articles/",
    "labview": "https://habr.com/ru/rss/hubs/labview/articles/",
    "laravel": "https://habr.com/ru/rss/hubs/laravel/articles/",
    "lasers": "https://habr.com/ru/rss/hubs/lasers/articles/",
    "latex": "https://habr.com/ru/rss/hubs/latex/articles/",
    "learning_languages": "https://habr.com/ru/rss/hubs/learning_languages/articles/",
    "lib": "https://habr.com/ru/rss/hubs/lib/articles/",
    "lifehacks": "https://habr.com/ru/rss/hubs/lifehacks/articles/",
    "linux": "https://habr.com/ru/rss/hubs/linux/articles/",
    "linux_dev": "https://habr.com/ru/rss/hubs/linux_dev/articles/",
    "lisp": "https://habr.com/ru/rss/hubs/lisp/articles/",
    "livestreet": "https://habr.com/ru/rss/hubs/livestreet/articles/",
    "localization": "https://habr.com/ru/rss/hubs/localization/articles/",
    "logic_games": "https://habr.com/ru/rss/hubs/logic_games/articles/",
    "lua": "https://habr.com/ru/rss/hubs/lua/articles/",
    "machine_learning": "https://habr.com/ru/rss/hubs/machine_learning/articles/",
    "macos_dev": "https://habr.com/ru/rss/hubs/osx_dev/articles/",
    "magento": "https://habr.com/ru/rss/hubs/magento/articles/",
    "map_api": "https://habr.com/ru/rss/hubs/map_api/articles/",
    "maths": "https://habr.com/ru/rss/hubs/maths/articles/",
    "matlab": "https://habr.com/ru/rss/hubs/matlab/articles/",
    "medgadgets": "https://habr.com/ru/rss/hubs/medgadgets/articles/",
    "media_management": "https://habr.com/ru/rss/hubs/media_management/articles/",
    "mercurial": "https://habr.com/ru/rss/hubs/mercurial/articles/",
    "mesh_networking": "https://habr.com/ru/rss/hubs/mesh_networking/articles/",
    "meteorjs": "https://habr.com/ru/rss/hubs/meteorjs/articles/",
    "microformats": "https://habr.com/ru/rss/hubs/microformats/articles/",
    "microservices": "https://habr.com/ru/rss/hubs/microservices/articles/",
    "mobile_analytics": "https://habr.com/ru/rss/hubs/mobileanalytics/articles/",
    "mobile_dev": "https://habr.com/ru/rss/hubs/mobile_dev/articles/",
    "mobile_monetization": "https://habr.com/ru/rss/hubs/mobile_monetization/articles/",
    "mobile_testing": "https://habr.com/ru/rss/hubs/mobile_testing/articles/",
    "mobileanalytics": "https://habr.com/ru/rss/hubs/mobileanalytics/articles/",
    "modx": "https://habr.com/ru/rss/hubs/modx/articles/",
    "mongodb": "https://habr.com/ru/rss/hubs/mongodb/articles/",
    "mono": "https://habr.com/ru/rss/hubs/mono/articles/",
    "mootools": "https://habr.com/ru/rss/hubs/mootools/articles/",
    "ms_access": "https://habr.com/ru/rss/hubs/ms_access/articles/",
    "mssql": "https://habr.com/ru/rss/hubs/mssql/articles/",
    "multicopters": "https://habr.com/ru/rss/hubs/multicopters/articles/",
    "music": "https://habr.com/ru/rss/hubs/sound/articles/",
    "mysql": "https://habr.com/ru/rss/hubs/mysql/articles/",
    "nano": "https://habr.com/ru/rss/hubs/nano/articles/",
    "natural_language_processing": "https://habr.com/ru/rss/hubs/natural_language_processing/articles/",
    "net": "https://habr.com/ru/rss/hubs/net/articles/",
    "netdev": "https://habr.com/ru/rss/hubs/netdev/articles/",
    "network_hardware": "https://habr.com/ru/rss/hubs/network_hardware/articles/",
    "network_standarts": "https://habr.com/ru/rss/hubs/network_standarts/articles/",
    "network_technologies": "https://habr.com/ru/rss/hubs/network_technologies/articles/",
    "nestjs": "https://habr.com/ru/rss/hubs/nestjs/articles/",
    "nginx": "https://habr.com/ru/rss/hubs/nginx/articles/",
    "nix": "https://habr.com/ru/rss/hubs/nix/articles/",
    "nodejs": "https://habr.com/ru/rss/hubs/nodejs/articles/",
    "nosql": "https://habr.com/ru/rss/hubs/nosql/articles/",
    "notebooks": "https://habr.com/ru/rss/hubs/notebooks/articles/",
    "nx": "https://habr.com/ru/rss/hubs/nx/articles/",
    "objectivec": "https://habr.com/ru/rss/hubs/objectivec/articles/",
    "office": "https://habr.com/ru/rss/hubs/office/articles/",
    "office365dev": "https://habr.com/ru/rss/hubs/office365dev/articles/",
    "oop": "https://habr.com/ru/rss/hubs/oop/articles/",
    "open_source": "https://habr.com/ru/rss/hubs/open_source/articles/",
    "openshift": "https://habr.com/ru/rss/hubs/openshift/articles/",
    "openstreetmap": "https://habr.com/ru/rss/hubs/openstreetmap/articles/",
    "opendata": "https://habr.com/ru/rss/hubs/opendata/articles/",
    "opera": "https://habr.com/ru/rss/hubs/opera/articles/",
    "oracle": "https://habr.com/ru/rss/hubs/oracle/articles/",
    "os": "https://habr.com/ru/rss/hubs/os/articles/",
    "osx_dev": "https://habr.com/ru/rss/hubs/osx_dev/articles/",
    "p2p": "https://habr.com/ru/rss/hubs/p2p/articles/",
    "parallel_programming": "https://habr.com/ru/rss/hubs/parallel_programming/articles/",
    "patents": "https://habr.com/ru/rss/hubs/patents/articles/",
    "pay_system": "https://habr.com/ru/rss/hubs/pay_system/articles/",
    "pdf": "https://habr.com/ru/rss/hubs/pdf/articles/",
    "perl": "https://habr.com/ru/rss/hubs/perl/articles/",
    "Peripheral": "https://habr.com/ru/rss/hubs/Peripheral/articles/",
    "phalcon": "https://habr.com/ru/rss/hubs/phalcon/articles/",
    "photo": "https://habr.com/ru/rss/hubs/photo/articles/",
    "php": "https://habr.com/ru/rss/hubs/php/articles/",
    "physics": "https://habr.com/ru/rss/hubs/physics/articles/",
    "pm": "https://habr.com/ru/rss/hubs/pm/articles/",
    "popular_science": "https://habr.com/ru/rss/hubs/popular_science/articles/",
    "postgresql": "https://habr.com/ru/rss/hubs/postgresql/articles/",
    "powershell": "https://habr.com/ru/rss/hubs/powershell/articles/",
    "presentation": "https://habr.com/ru/rss/hubs/presentation/articles/",
    "processing_lang": "https://habr.com/ru/rss/hubs/processing_lang/articles/",
    "productpm": "https://habr.com/ru/rss/hubs/productpm/articles/",
    "prolog": "https://habr.com/ru/rss/hubs/prolog/articles/",
    "programming": "https://habr.com/ru/rss/hubs/programming/articles/",
    "prototyping": "https://habr.com/ru/rss/hubs/prototyping/articles/",
    "puppet": "https://habr.com/ru/rss/hubs/puppet/articles/",
    "python": "https://habr.com/ru/rss/hubs/python/articles/",
    "qt_software": "https://habr.com/ru/rss/hubs/qt_software/articles/",
    "quantum": "https://habr.com/ru/rss/hubs/quantum/articles/",
    "r": "https://habr.com/ru/rss/hubs/r/articles/",
    "radio-communications": "https://habr.com/ru/rss/hubs/radio-communications/articles/",
    "raspberrypi": "https://habr.com/ru/rss/hubs/raspberrypi/articles/",
    "react-native": "https://habr.com/ru/rss/hubs/react-native/articles/",
    "reactjs": "https://habr.com/ru/rss/hubs/reactjs/articles/",
    "read": "https://habr.com/ru/rss/hubs/read/articles/",
    "refactoring": "https://habr.com/ru/rss/hubs/refactoring/articles/",
    "regex": "https://habr.com/ru/rss/hubs/regex/articles/",
    "remote": "https://habr.com/ru/rss/hubs/remote/articles/",
    "research": "https://habr.com/ru/rss/hubs/research/articles/",
    "reverse-engineering": "https://habr.com/ru/rss/hubs/reverse-engineering/articles/",
    "robot": "https://habr.com/ru/rss/hubs/robot/articles/",
    "ror": "https://habr.com/ru/rss/hubs/ror/articles/",
    "ruby": "https://habr.com/ru/rss/hubs/ruby/articles/",
    "rust": "https://habr.com/ru/rss/hubs/rust/articles/",
    "s_admin": "https://habr.com/ru/rss/hubs/s_admin/articles/",
    "saas": "https://habr.com/ru/rss/hubs/saas/articles/",
    "safari": "https://habr.com/ru/rss/hubs/safari/articles/",
    "Sailfish_dev": "https://habr.com/ru/rss/hubs/Sailfish_dev/articles/",
    "sales": "https://habr.com/ru/rss/hubs/sales/articles/",
    "san": "https://habr.com/ru/rss/hubs/san/articles/",
    "scala": "https://habr.com/ru/rss/hubs/scala/articles/",
    "scada": "https://habr.com/ru/rss/hubs/scada/articles/",
    "sci-fi": "https://habr.com/ru/rss/hubs/sci-fi/articles/",
    "search_technologies": "https://habr.com/ru/rss/hubs/search_technologies/articles/",
    "seo": "https://habr.com/ru/rss/hubs/seo/articles/",
    "server_side_optimization": "https://habr.com/ru/rss/hubs/server_side_optimization/articles/",
    "serverless": "https://habr.com/ru/rss/hubs/serverless/articles/",
    "service_desk": "https://habr.com/ru/rss/hubs/service_desk/articles/",
    "shells": "https://habr.com/ru/rss/hubs/shells/articles/",
    "sharepoint": "https://habr.com/ru/rss/hubs/sharepoint/articles/",
    "silverlight": "https://habr.com/ru/rss/hubs/silverlight/articles/",
    "smallbasic": "https://habr.com/ru/rss/hubs/smallbasic/articles/",
    "smalltalk": "https://habr.com/ru/rss/hubs/smalltalk/articles/",
    "smartphones": "https://habr.com/ru/rss/hubs/smartphones/articles/",
    "smol": "https://habr.com/ru/rss/hubs/smol/articles/",
    "social_networks": "https://habr.com/ru/rss/hubs/social_networks/articles/",
    "soft": "https://habr.com/ru/rss/hubs/soft/articles/",
    "solidity": "https://habr.com/ru/rss/hubs/solidity/articles/",
    "sound": "https://habr.com/ru/rss/hubs/sound/articles/",
    "space": "https://habr.com/ru/rss/hubs/space/articles/",
    "spam": "https://habr.com/ru/rss/hubs/spam/articles/",
    "sphinx": "https://habr.com/ru/rss/hubs/sphinx/articles/",
    "sport_programming": "https://habr.com/ru/rss/hubs/sport_programming/articles/",
    "sql": "https://habr.com/ru/rss/hubs/sql/articles/",
    "sqlite": "https://habr.com/ru/rss/hubs/sqlite/articles/",
    "startuprise": "https://habr.com/ru/rss/hubs/startuprise/articles/",
    "statistics": "https://habr.com/ru/rss/hubs/statistics/articles/",
    "storages": "https://habr.com/ru/rss/hubs/storages/articles/",
    "study": "https://habr.com/ru/rss/hubs/study/articles/",
    "supercomputers": "https://habr.com/ru/rss/hubs/supercomputers/articles/",
    "sveltejs": "https://habr.com/ru/rss/hubs/sveltejs/articles/",
    "sw": "https://habr.com/ru/rss/hubs/sw/articles/",
    "swift": "https://habr.com/ru/rss/hubs/swift/articles/",
    "symfony": "https://habr.com/ru/rss/hubs/symfony/articles/",
    "sys_admin": "https://habr.com/ru/rss/hubs/sys_admin/articles/",
    "system_programming": "https://habr.com/ru/rss/hubs/system_programming/articles/",
    "tablets": "https://habr.com/ru/rss/hubs/tablets/articles/",
    "tarantool": "https://habr.com/ru/rss/hubs/tarantool/articles/",
    "tdd": "https://habr.com/ru/rss/hubs/tdd/articles/",
    "technical_writing": "https://habr.com/ru/rss/hubs/technical_writing/articles/",
    "tech_events": "https://habr.com/ru/rss/hubs/tech_events/articles/",
    "telemedicine": "https://habr.com/ru/rss/hubs/telemedicine/articles/",
    "tensorflow": "https://habr.com/ru/rss/hubs/tensorflow/articles/",
    "terminator": "https://habr.com/ru/rss/hubs/terminator/articles/",
    "tizen_dev": "https://habr.com/ru/rss/hubs/tizen_dev/articles/",
    "transport": "https://habr.com/ru/rss/hubs/transport/articles/",
    "twisted": "https://habr.com/ru/rss/hubs/twisted/articles/",
    "txt_ide": "https://habr.com/ru/rss/hubs/txt_ide/articles/",
    "typo3": "https://habr.com/ru/rss/hubs/typo3/articles/",
    "typescript": "https://habr.com/ru/rss/hubs/typescript/articles/",
    "typography": "https://habr.com/ru/rss/hubs/typography/articles/",
    "UEFI": "https://habr.com/ru/rss/hubs/UEFI/articles/",
    "ui": "https://habr.com/ru/rss/hubs/ui/articles/",
    "uml": "https://habr.com/ru/rss/hubs/uml/articles/",
    "unity": "https://habr.com/ru/rss/hubs/unity/articles/",
    "unreal_engine": "https://habr.com/ru/rss/hubs/unreal_engine/articles/",
    "urban": "https://habr.com/ru/rss/hubs/urban/articles/",
    "usability": "https://habr.com/ru/rss/hubs/usability/articles/",
    "vba": "https://habr.com/ru/rss/hubs/vba/articles/",
    "venturecap": "https://habr.com/ru/rss/hubs/venturecap/articles/",
    "vector_graphics": "https://habr.com/ru/rss/hubs/vector_graphics/articles/",
    "video": "https://habr.com/ru/rss/hubs/video/articles/",
    "video_conferencing": "https://habr.com/ru/rss/hubs/video_conferencing/articles/",
    "video_tech": "https://habr.com/ru/rss/hubs/video_tech/articles/",
    "videocards": "https://habr.com/ru/rss/hubs/videocards/articles/",
    "vim": "https://habr.com/ru/rss/hubs/vim/articles/",
    "virtualization": "https://habr.com/ru/rss/hubs/virtualization/articles/",
    "virus": "https://habr.com/ru/rss/hubs/virus/articles/",
    "visual_programming": "https://habr.com/ru/rss/hubs/visual_programming/articles/",
    "vk_api": "https://habr.com/ru/rss/hubs/vk_api/articles/",
    "voice_interfaces": "https://habr.com/ru/rss/hubs/voice_interfaces/articles/",
    "vs": "https://habr.com/ru/rss/hubs/vs/articles/",
    "vuejs": "https://habr.com/ru/rss/hubs/vuejs/articles/",
    "wearable_electronics": "https://habr.com/ru/rss/hubs/wearable_electronics/articles/",
    "web_monetization": "https://habr.com/ru/rss/hubs/web_monetization/articles/",
    "web_testing": "https://habr.com/ru/rss/hubs/web_testing/articles/",
    "weban": "https://habr.com/ru/rss/hubs/weban/articles/",
    "webassembly": "https://habr.com/ru/rss/hubs/webassembly/articles/",
    "webdev": "https://habr.com/ru/rss/hubs/webdev/articles/",
    "webdesign": "https://habr.com/ru/rss/hubs/web_design/articles/",
    "webgl": "https://habr.com/ru/rss/hubs/webgl/articles/",
    "web_design": "https://habr.com/ru/rss/hubs/web_design/articles/",
    "wiki": "https://habr.com/ru/rss/hubs/wiki/articles/",
    "win_dev": "https://habr.com/ru/rss/hubs/win_dev/articles/",
    "windows": "https://habr.com/ru/rss/hubs/win_dev/articles/",
    "wireless": "https://habr.com/ru/rss/hubs/wireless/articles/",
    "wordpress": "https://habr.com/ru/rss/hubs/wordpress/articles/",
    "wp_dev": "https://habr.com/ru/rss/hubs/wp_dev/articles/",
    "Xamarin": "https://habr.com/ru/rss/hubs/Xamarin/articles/",
    "x_api": "https://habr.com/ru/rss/hubs/x_api/articles/",
    "xcode": "https://habr.com/ru/rss/hubs/xcode/articles/",
    "xml": "https://habr.com/ru/rss/hubs/xml/articles/",
    "xslt": "https://habr.com/ru/rss/hubs/xslt/articles/",
    "yandex_api": "https://habr.com/ru/rss/hubs/yandex_api/articles/",
    "yii": "https://habr.com/ru/rss/hubs/yii/articles/",
    "zadachki": "https://habr.com/ru/rss/hubs/zadachki/articles/",
    "zend_framework": "https://habr.com/ru/rss/hubs/zend_framework/articles/",
    "zig": "https://habr.com/ru/rss/hubs/zig/articles/"
};

window.LIFEHACKER_CATEGORIES = {
    "Android": "https://lifehacker.ru/topics/technology/android/feed/",
    "Авто": "https://lifehacker.ru/topics/auto/feed/",
    "Браузеры": "https://lifehacker.ru/topics/technology/browsers/feed/",
    "Вдохновение": "https://lifehacker.ru/topics/inspiration/feed/",
    "Веб-сервисы": "https://lifehacker.ru/topics/technology/web-services/feed/",
    "Видео": "https://lifehacker.ru/topics/video/feed/",
    "Выживание": "https://lifehacker.ru/topics/survival/feed/",
    "Дачный сезон": "https://lifehacker.ru/topics/dacha/feed/",
    "Еда": "https://lifehacker.ru/topics/food/feed/",
    "Жизнь": "https://lifehacker.ru/topics/life/feed/",
    "Игры": "https://lifehacker.ru/topics/relax/games/feed/",
    "Интернет": "https://lifehacker.ru/topics/internet/feed/",
    "iOS": "https://lifehacker.ru/topics/technology/ios/feed/",
    "Кино": "https://lifehacker.ru/topics/relax/movies/feed/",
    "Книги": "https://lifehacker.ru/topics/relax/books/feed/",
    "Колонка": "https://lifehacker.ru/topics/kolonka/feed/",
    "Ликбез": "https://lifehacker.ru/topics/basic/feed/",
    "macOS": "https://lifehacker.ru/topics/technology/mac-os/feed/",
    "Мотивация": "https://lifehacker.ru/topics/motivation/feed/",
    "Музыка": "https://lifehacker.ru/topics/relax/music/feed/",
    "Новости": "https://lifehacker.ru/topics/news/feed/",
    "Образование": "https://lifehacker.ru/topics/work/education/feed/",
    "Ответы": "https://lifehacker.ru/topics/answers/feed/",
    "Отдых": "https://lifehacker.ru/topics/relax/feed/",
    "Отношения": "https://lifehacker.ru/topics/communication/feed/",
    "Подкасты": "https://lifehacker.ru/topics/podcast/feed/",
    "Покупки": "https://lifehacker.ru/topics/shopping/feed/",
    "Право": "https://lifehacker.ru/topics/pravo/feed/",
    "Праздники": "https://lifehacker.ru/topics/relax/holidays/feed/",
    "Пресс-релизы": "https://lifehacker.ru/topics/press/feed/",
    "Продуктивность": "https://lifehacker.ru/topics/work/productivity/feed/",
    "Путешествия": "https://lifehacker.ru/topics/relax/travel/feed/",
    "Работа и учёба": "https://lifehacker.ru/topics/work/feed/",
    "Рабочие места": "https://lifehacker.ru/topics/work/workplaces/feed/",
    "Редакция": "https://lifehacker.ru/topics/editorial/feed/",
    "Своё дело": "https://lifehacker.ru/topics/work/entrepreneur/feed/",
    "Сделай сам": "https://lifehacker.ru/topics/diy/feed/",
    // "Секс": "https://lifehacker.ru/topics/sex/feed/" — УДАЛЕНО
    "Советы": "https://lifehacker.ru/topics/advices/feed/",
    "Стать богатым": "https://lifehacker.ru/topics/finances/feed/",
    "Тесты": "https://lifehacker.ru/topics/relax/testy/feed/",
    "Технологии": "https://lifehacker.ru/topics/technology/feed/",
    "Устройства": "https://lifehacker.ru/topics/technology/gadgets/feed/",
    "Фото": "https://lifehacker.ru/topics/relax/foto/feed/",
    "Windows": "https://lifehacker.ru/topics/technology/windows/feed/"
};

window.VC_CATEGORIES = {
    "Образование": "https://vc.ru/education",
    "Мнения": "https://vc.ru/opinions",
    "Будущее": "https://vc.ru/future",
    "Видео": "https://vc.ru/video",
    "Apple": "https://vc.ru/apple",
    "ChatGPT": "https://vc.ru/chatgpt",
    "Midjourney": "https://vc.ru/midjourney",
    "Медиа": "https://vc.ru/media",
    "Соцсети": "https://vc.ru/social",
    "Деньги": "https://vc.ru/money",
    "Транспорт": "https://vc.ru/transport",
    "Маркетинг": "https://vc.ru/marketing",
    "SEO": "https://vc.ru/seo",
    "Крипто": "https://vc.ru/crypto",
    "Миграция": "https://vc.ru/migration",
    "Дизайн": "https://vc.ru/design",
    "Путешествия": "https://vc.ru/travel",
    "Офлайн": "https://vc.ru/offline",
    "Телеграм": "https://vc.ru/telegram",
    "AI": "https://vc.ru/ai",
    "Еда": "https://vc.ru/food",
    "Сервисы": "https://vc.ru/services",
    "Офис": "https://vc.ru/office",
    "Кейсы роста": "https://vc.ru/growth",
    "Ритейл": "https://vc.ru/retail"
};

window.INTERIORS_CATEGORIES = {
    "Arch Digest": "https://www.architecturaldigest.com/feed/rss",
    "Decoist": "https://www.decoist.com/feed/",
    "DesMilk Interiors": "https://design-milk.com/category/interior-design/feed/",
    "Designboom Int": "https://www.designboom.com/design/feed/",
    "Dezeen Interiors": "https://www.dezeen.com/interiors/feed/",
    "Domino": "https://www.domino.com/feed",
    "Dwell": "https://www.dwell.com/@dwell/rss",
    "Elle Decor": "https://www.elledecor.com/rss/all.xml",
    "House Beautiful": "https://www.housebeautiful.com/rss/all.xml",
    "IN/EX": "https://t.me/inexmagazine",
    "И+Д": "https://t.me/interiorplusdesign",
    "Livingetc": "https://www.livingetc.com/feeds.xml",
    "Remodelista": "https://www.remodelista.com/feed/",
    "ТопДизайнМаг": "https://t.me/topdesignmag",
    "WA Journal": "https://t.me/thewajournal",
    "WoL": "https://t.me/wolmagazine"
};

window.ARCHITECTURE_CATEGORIES = {
    "ArchDaily": "https://feeds.feedburner.com/Archdaily",
    "ArchEyes": "https://archeyes.com/feed",
    "Archinect": "https://archinect.com/feed/1/news",
    "Architizer": "https://architizer.com/blog/feed",
    "Archpaper": "https://archpaper.com/feed",
    "ArchiTime": "https://www.architime.ru/",
    "Архидом": "https://vk.com/archidomonline",
    "Архи.ру": "https://archi.ru/rss.xml",
    "DesMilk Arch": "https://design-milk.com/category/architecture/feed/",
    "Designboom Arch": "https://www.designboom.com/architecture/feed/",
    "Dezeen Arch": "https://www.dezeen.com/architecture/feed/",
    "The Guardian Arch": "https://www.theguardian.com/artanddesign/architecture/rss",
    "Yanko Design": "https://www.yankodesign.com/category/architecture/feed/"
};

window.ART_CATEGORIES = {
    "ArtForum": "https://www.artforum.com/feed",
    "ARTinvestment": "https://vk.com/artinvestmentru",
    "ArtSpiel": "https://artspiel.org/feed/",
    "ARTnews": "https://www.artnews.com/feed/",
    "Artsy Shark": "https://www.artsyshark.com/feed/",
    "Booooooom": "https://www.booooooom.com/feed/",
    "Colossal": "https://www.thisiscolossal.com/feed/",
    "ContArtDaily": "https://contemporaryartdaily.com/feed/",
    "HiFructose": "https://hifructose.com/feed/",
    "Hyperallergic": "https://hyperallergic.com/feed/",
    "Jackson’s Art": "https://www.jacksonsart.com/blog/feed/",
    "Juxtapoz": "https://www.juxtapoz.com/feed/",
    "The Guardian Art": "https://www.theguardian.com/artanddesign/art/rss",
    "The Guardian Photo": "https://www.theguardian.com/artanddesign/photography/rss"
};

window.BBC_CATEGORIES = {
    "Австралия": "http://feeds.bbci.co.uk/news/world/australia/rss.xml",
    "Азия": "http://feeds.bbci.co.uk/news/world/asia/rss.xml",
    "Англия": "http://feeds.bbci.co.uk/news/england/rss.xml",
    "Африка": "http://feeds.bbci.co.uk/news/world/africa/rss.xml",
    "Бизнес": "http://feeds.bbci.co.uk/news/business/rss.xml",
    "Ближний Восток": "http://feeds.bbci.co.uk/news/world/middle_east/rss.xml",
    "Великобритания": "http://feeds.bbci.co.uk/news/uk/rss.xml",
    "Главные новости": "http://feeds.bbci.co.uk/news/rss.xml",
    "Европа": "http://feeds.bbci.co.uk/news/world/europe/rss.xml",
    "Здоровье": "http://feeds.bbci.co.uk/news/health/rss.xml",
    "Искусство и развлечения": "http://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml",
    "Латинская Америка": "http://feeds.bbci.co.uk/news/world/latin_america/rss.xml",
    "Мир": "http://feeds.bbci.co.uk/news/world/rss.xml",
    "Наука и экология": "http://feeds.bbci.co.uk/news/science_and_environment/rss.xml",
    "Образование": "http://feeds.bbci.co.uk/news/education/rss.xml",
    "Политика": "http://feeds.bbci.co.uk/news/politics/rss.xml",
    "Северная Ирландия": "http://feeds.bbci.co.uk/news/northern_ireland/rss.xml",
    "США и Канада": "http://feeds.bbci.co.uk/news/world/us_and_canada/rss.xml",
    "Технологии": "http://feeds.bbci.co.uk/news/technology/rss.xml",
    "Уэльс": "http://feeds.bbci.co.uk/news/wales/rss.xml",
    "Шотландия": "http://feeds.bbci.co.uk/news/scotland/rss.xml"
};

window.CNN_CATEGORIES = {
    "Азия": "http://rss.cnn.com/rss/edition_asia.rss",
    "Америка": "http://rss.cnn.com/rss/edition_americas.rss",
    "Африка": "http://rss.cnn.com/rss/edition_africa.rss",
    "Бизнес": "http://rss.cnn.com/rss/edition_business.rss",
    "Ближний Восток": "http://rss.cnn.com/rss/edition_meast.rss",
    "Главные новости": "http://rss.cnn.com/rss/edition.rss",
    "Европа": "http://rss.cnn.com/rss/edition_europe.rss",
    "Мир": "http://rss.cnn.com/rss/edition_world.rss",
    "Путешествия": "http://rss.cnn.com/rss/edition_travel.rss",
    "Спорт": "http://rss.cnn.com/rss/edition_sport.rss",
    "США": "http://rss.cnn.com/rss/edition_us.rss",
    "Технологии": "http://rss.cnn.com/rss/edition_technology.rss"
};
